OA_API_KEY = "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"
OA_API_KEY_2 = "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"
OA_API_KEY_3 = "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"
XI_API_KEY = ""
